--MEDIUM LEVEL

CREATE TABLE DEPARTMENT (
    ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(50)
);

INSERT INTO DEPARTMENT (ID, DEPT_NAME) VALUES
(1, 'IT'),
(2, 'SALES');

CREATE TABLE EMPLOYEE (
    ID INT,
    NAME VARCHAR(50),
    SALARY INT,
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID)
);

INSERT INTO EMPLOYEE (ID, NAME, SALARY, DEPT_ID) VALUES
(1, 'JOE', 70000, 1),
(2, 'JIM', 90000, 1),
(3, 'HENRY', 80000, 2),
(4, 'SAM', 60000, 2),
(5, 'MAX', 90000, 1);

SELECT D.DEPT_NAME, E.NAME, E.SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPT_ID = D.ID
WHERE E.SALARY = (
    SELECT MAX(E2.SALARY)
    FROM EMPLOYEE E2
    WHERE E2.DEPT_ID = E.DEPT_ID
)
ORDER BY D.DEPT_NAME, E.NAME;

--HARD LEVEL

CREATE TABLE A (
    EMPID INT,
    ENAME VARCHAR(50),
    SALARY INT
);

INSERT INTO A (EMPID, ENAME, SALARY) VALUES
(1, 'AA', 1000),
(2, 'BB', 300);

CREATE TABLE B (
    EMPID INT,
    ENAME VARCHAR(50),
    SALARY INT
);

INSERT INTO B (EMPID, ENAME, SALARY) VALUES
(2, 'BB', 400),
(3, 'CC', 100);

SELECT EMPID, ENAME, MIN(SALARY) AS SALARY
FROM (
    SELECT * FROM A
    UNION ALL
    SELECT * FROM B
) AS MERGED
GROUP BY EMPID, ENAME;








