DROP TABLE IF EXISTS TBL_LEARNERS;

CREATE TABLE TBL_LEARNERS (
    LID SERIAL PRIMARY KEY,
    LNAME VARCHAR(50) UNIQUE,
    LAGE INT,
    LCLASS INT
);

DO $$
BEGIN TRANSACTION
    BEGIN
        INSERT INTO TBL_LEARNERS(LNAME, LAGE, LCLASS) VALUES ('PRIYA',15,7);
        INSERT INTO TBL_LEARNERS(LNAME, LAGE, LCLASS) VALUES ('ROHAN',16,8);
        INSERT INTO TBL_LEARNERS(LNAME, LAGE, LCLASS) VALUES ('KAVYA',17,9);
        RAISE NOTICE 'TRANSACTION SUCCESSFULLY COMPLETED';
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'TRANSACTION FAILED..! ROLLING BACK CHANGES.';
        RAISE;
    END;
END;
$$;

SELECT * FROM TBL_LEARNERS;

DO $$
BEGIN TRANSACTION
    BEGIN
        INSERT INTO TBL_LEARNERS(LNAME, LAGE, LCLASS) VALUES ('PRIYA',15,7);
        INSERT INTO TBL_LEARNERS(LNAME, LAGE, LCLASS) VALUES ('ROHAN',16,8);
        INSERT INTO TBL_LEARNERS(LNAME, LAGE, LCLASS) VALUES ('PRIYA',17,9);
        INSERT INTO TBL_LEARNERS(LNAME, LAGE, LCLASS) VALUES ('KAVYA',18,10);
        RAISE NOTICE 'TRANSACTION SUCCESSFULLY COMPLETED';
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'TRANSACTION FAILED..! ROLLING BACK CHANGES.';
        RAISE;
    END;
END;
$$;
