--MEDIUM 

CREATE OR REPLACE FUNCTION STUDENT_AUDIT_FN()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        RAISE NOTICE 'INSERTED -> ID: %, NAME: %, AGE: %, CLASS: %', NEW.SID, NEW.SNAME, NEW.SAGE, NEW.SCLASS;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        RAISE NOTICE 'DELETED -> ID: %, NAME: %, AGE: %, CLASS: %', OLD.SID, OLD.SNAME, OLD.SAGE, OLD.SCLASS;
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$;


-- HARD 

CREATE TABLE TBL_STAFF (
    STAFF_ID SERIAL PRIMARY KEY,
    STAFF_NAME VARCHAR(100) NOT NULL,
    STAFF_SALARY NUMERIC
);

CREATE TABLE TBL_STAFF_AUDIT (
    SNO SERIAL PRIMARY KEY,
    LOG_MESSAGE TEXT
);

CREATE OR REPLACE FUNCTION STAFF_AUDIT_FN()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO TBL_STAFF_AUDIT(LOG_MESSAGE)
        VALUES ('STAFF MEMBER ' || NEW.STAFF_NAME || ' ADDED ON ' || NOW());
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO TBL_STAFF_AUDIT(LOG_MESSAGE)
        VALUES ('STAFF MEMBER ' || OLD.STAFF_NAME || ' REMOVED ON ' || NOW());
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER TRG_STAFF_AUDIT
AFTER INSERT OR DELETE
ON TBL_STAFF
FOR EACH ROW
EXECUTE FUNCTION STAFF_AUDIT_FN();

INSERT INTO TBL_STAFF(STAFF_NAME, STAFF_SALARY) VALUES ('RAHUL', 65000);
DELETE FROM TBL_STAFF WHERE STAFF_NAME = 'RAHUL';
SELECT * FROM TBL_STAFF_AUDIT;

